### ISSUE TITLE
Error in More_with_BERT_and_GPT.ipynb

### ISSUE THREAD

**Issue by collegewap** [sinanuozdemir/oreilly-transformers-video-series#2]
I get the following error when I run the notebook More_with_BERT_and_GPT.ipynb in Google Colab. I haven't made any changes to the notebook.

![image](https://github.com/sinanuozdemir/oreilly-transformers-video-series/assets/9767383/f7ba0d19-8fcb-4fb2-847b-edfd7dc49d42)

**Comment by sinanuozdemir** [comment]
Good catch and thank you for making an issue! I have updated the code in this PR #3 

I hope you're enjoying the course and code :)
